// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.BackstageTabItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.Button.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.CheckBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.ComboBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.DropDownButton.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.GalleryItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.InRibbonGallery.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.MenuItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.RadioButton.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.RibbonControl.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.RibbonGroupBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.RibbonTabItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.TextBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Fluent.ToggleButton.KeyTipProperty")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.BackstageTabItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.Button.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.CheckBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.ComboBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.DropDownButton.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.GalleryItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.InRibbonGallery.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.MenuItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.RadioButton.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.RibbonControl.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.RibbonGroupBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.RibbonTabItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.TextBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Fluent.ToggleButton.KeyTip")]