<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <Nullable>enable</Nullable>
    <LangVersion>latestmajor</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn)</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluent.Ribbon\Fluent.Ribbon.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Update="Microsoft.CodeAnalysis.CSharp" PrivateAssets="none" IncludeAssets="all" />
  </ItemGroup>
</Project>
